
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 --quiet
          haxelib install lime 8.0.2 --quiet
          haxelib install openfl 9.2.2 --quiet
          haxelib install flixel 5.3.1 --quiet
          haxelib install flixel-addons 3.1.0 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install hscript --quiet
          haxelib install SScript --quiet
          haxelib git linc_luajit https://github.com/larsiusprime/linc_luajit --quiet
          haxelib install actuate --quiet
          haxelib install hxCodec --quiet

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Configure Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME

      - name: Build Android
        run: haxelib run lime build android -final

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PsychEngineAndroid
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
